### ISSUE TITLE
Most recent docker image release is not tagged as latest/an ancient release is tagged latest

### ISSUE THREAD

**Issue by agreenhalgh** [NHSDigital/integration-adaptor-mhs#154]
The image tagged as latest is actually a few years old, and more recent releases not tagged latest. This is likely to result in other projects pulling old versions.

![image](https://github.com/NHSDigital/integration-adaptor-mhs/assets/6201362/260fe513-13dc-42c9-94ad-2722db2644f0)

**Comment by adrianclay** [comment]
😓 Thanks! Have removed the 4 year old "latest" tags.
